using System.Text;
using Jellyfin.Plugin.JellyShim.Transformation;
using Microsoft.Extensions.Logging;
using Moq;

namespace Jellyfin.Plugin.JellyShim.Tests;

public class SvgTransformerTests
{
    private readonly SvgTransformer _transformer;

    public SvgTransformerTests()
    {
        _transformer = new SvgTransformer(new Mock<ILogger<SvgTransformer>>().Object);
    }

    // ── Minify (static string method) ─────────────────────────────

    [Fact]
    public void Minify_RemovesXmlComments()
    {
        var svg = "<svg><!-- comment --><rect/></svg>";
        var result = SvgTransformer.Minify(svg);
        Assert.DoesNotContain("<!--", result);
        Assert.Contains("<rect/>", result);
    }

    [Fact]
    public void Minify_RemovesMultiLineXmlComments()
    {
        var svg = "<svg><!--\n  multi\n  line\n--><rect/></svg>";
        var result = SvgTransformer.Minify(svg);
        Assert.DoesNotContain("<!--", result);
        Assert.Contains("<rect/>", result);
    }

    [Fact]
    public void Minify_RemovesXmlDeclaration()
    {
        var svg = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><svg><rect/></svg>";
        var result = SvgTransformer.Minify(svg);
        Assert.DoesNotContain("<?xml", result);
        Assert.StartsWith("<svg>", result);
    }

    [Fact]
    public void Minify_RemovesDoctype()
    {
        var svg = "<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"><svg><rect/></svg>";
        var result = SvgTransformer.Minify(svg);
        Assert.DoesNotContain("DOCTYPE", result);
    }

    [Fact]
    public void Minify_RemovesMetadataElement()
    {
        var svg = "<svg><metadata><rdf:RDF>some data</rdf:RDF></metadata><rect/></svg>";
        var result = SvgTransformer.Minify(svg);
        Assert.DoesNotContain("metadata", result);
        Assert.Contains("<rect/>", result);
    }

    [Fact]
    public void Minify_RemovesSodipodiElements()
    {
        var svg = "<svg><sodipodi:namedview id=\"nv\" pagecolor=\"#fff\"/><rect/></svg>";
        var result = SvgTransformer.Minify(svg);
        Assert.DoesNotContain("sodipodi", result);
        Assert.Contains("<rect/>", result);
    }

    [Fact]
    public void Minify_RemovesEditorAttributes()
    {
        var svg = "<svg inkscape:version=\"1.0\" sodipodi:docname=\"test.svg\"><rect sketch:type=\"MSRect\"/></svg>";
        var result = SvgTransformer.Minify(svg);
        Assert.DoesNotContain("inkscape:", result);
        Assert.DoesNotContain("sodipodi:", result);
        Assert.DoesNotContain("sketch:", result);
    }

    [Fact]
    public void Minify_RemovesDataNameAttributes()
    {
        var svg = "<svg><rect data-name:label=\"test\"/></svg>";
        var result = SvgTransformer.Minify(svg);
        Assert.DoesNotContain("data-name:", result);
    }

    [Fact]
    public void Minify_RemovesEmptyIdAttributes()
    {
        var svg = "<svg><rect id=\"\"/></svg>";
        var result = SvgTransformer.Minify(svg);
        Assert.DoesNotContain("id=\"\"", result);
    }

    [Fact]
    public void Minify_PreservesNonEmptyIdAttributes()
    {
        var svg = "<svg><rect id=\"myRect\"/></svg>";
        var result = SvgTransformer.Minify(svg);
        Assert.Contains("id=\"myRect\"", result);
    }

    [Fact]
    public void Minify_CollapsesInterTagWhitespace()
    {
        var svg = "<svg>  \n  <rect/>  \n  <circle/>  \n</svg>";
        var result = SvgTransformer.Minify(svg);
        Assert.Contains("><rect/><circle/><", result);
    }

    [Fact]
    public void Minify_CollapsesMultipleWhitespace()
    {
        var svg = "<svg    viewBox=\"0  0  100  100\"><rect/></svg>";
        var result = SvgTransformer.Minify(svg);
        Assert.DoesNotContain("    ", result);
    }

    [Fact]
    public void Minify_TrimsLeadingAndTrailingWhitespace()
    {
        var svg = "  \n <svg><rect/></svg>  \n ";
        var result = SvgTransformer.Minify(svg);
        Assert.Equal("<svg><rect/></svg>", result);
    }

    [Fact]
    public void Minify_FullSvgWithAllNoise()
    {
        var svg = """
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
            <!-- Generated by Inkscape -->
            <svg xmlns="http://www.w3.org/2000/svg" inkscape:version="1.2" sodipodi:docname="icon.svg"
                 viewBox="0 0 24 24">
              <metadata>
                <rdf:RDF>
                  <cc:Work rdf:about="">
                    <dc:format>image/svg+xml</dc:format>
                  </cc:Work>
                </rdf:RDF>
              </metadata>
              <sodipodi:namedview id="" pagecolor="#ffffff" bordercolor="#999999"/>
              <rect id="bg" width="24" height="24" fill="#000"/>
            </svg>
            """;
        var result = SvgTransformer.Minify(svg);

        Assert.DoesNotContain("<?xml", result);
        Assert.DoesNotContain("DOCTYPE", result);
        Assert.DoesNotContain("<!--", result);
        Assert.DoesNotContain("metadata", result);
        Assert.DoesNotContain("sodipodi:", result);
        Assert.DoesNotContain("inkscape:", result);
        Assert.Contains("id=\"bg\"", result);
        Assert.Contains("viewBox", result);
    }

    // ── MinifyBytes (instance byte[] method) ──────────────────────

    [Fact]
    public void MinifyBytes_ReducesSize()
    {
        var svg = "<?xml version=\"1.0\"?><!-- comment --><svg><metadata><x/></metadata><rect/></svg>";
        var input = Encoding.UTF8.GetBytes(svg);

        var result = _transformer.MinifyBytes(input);

        Assert.True(result.Length < input.Length,
            $"Expected smaller output: {result.Length} < {input.Length}");
        var str = Encoding.UTF8.GetString(result);
        Assert.Contains("<rect/>", str);
    }

    [Fact]
    public void MinifyBytes_ReturnsOriginal_WhenMinificationDoesNotReduce()
    {
        // This SVG has no noise to remove — minification won't reduce it
        var svg = "<svg><rect/></svg>";
        var input = Encoding.UTF8.GetBytes(svg);

        var result = _transformer.MinifyBytes(input);

        Assert.Same(input, result);
    }

    [Fact]
    public void MinifyBytes_EmptyInput_ReturnsSameInstance()
    {
        var input = Array.Empty<byte>();
        var result = _transformer.MinifyBytes(input);

        // Empty string after Minify + Trim → empty bytes → same length → return original
        Assert.Same(input, result);
    }
}
